package com.berlin.domain.model

data class Permission(
    val createProject: Boolean = false,
    val updateProject: Boolean = false,
    val deleteProject: Boolean = false,
    val createState: Boolean = false,
    val updateState: Boolean = false,
    val deleteState: Boolean = false,
    val viewTaskById: Boolean = false,
    val viewTasksByProject: Boolean = false,
    val createTask: Boolean = false,
    val updateTask: Boolean = false,
    val deleteTask: Boolean = false,
    val assignTask: Boolean = false,
    val changeTaskState: Boolean = false,
    val getTaskById: Boolean = false,
    val getTasksByProjectId: Boolean = false,
    val viewAuditLogs: Boolean = false,
    val getAllProjects: Boolean = false,
    val getProjectById: Boolean = false,
    val getAllStatesByProjectId: Boolean = false,
    val getStateById: Boolean = false,
    val getAuditByProject: Boolean = false,
    val getAuditByTask: Boolean = false,
    val getAuditByUser: Boolean = false,
    val createMate: Boolean = false,
    val fetchAllUsers: Boolean = false,
    val getLoggedInUsers: Boolean = false,
    val getUserById: Boolean = false,
)